[display-setting]
width	= 1080
height	= 720
format	= 32

[attribute-setting]
daemon	= 0
acclerate = 1
brightness = 255
sharemem = 0
shareone = 1

[system-setting]
simulator = 1
quitwait = 15

[mode-setting]
startdir = /opt/project-main/tinyPiXApp/Application/deskTop/bin/
startapp = PiXDesktop
