/* 项目名称,也是所有生成的源码文件名前缀 */

/*
 * Generated by erpcgen 1.14.0 on Fri Dec 12 15:17:41 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_TpAppManager_common_hpp_)
#define _TpAppManager_common_hpp_


#include <cstddef>
#include <cstdint>

#include "erpc_version.h"

#if 11400 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif


#if !defined(ERPC_TYPE_DEFINITIONS_TPAPPMANAGER)
#define ERPC_TYPE_DEFINITIONS_TPAPPMANAGER

// Aliases data types declarations
typedef struct binary_t binary_t;

// Structures/unions data types declarations
struct binary_t
{
    uint8_t * data;
    uint32_t dataLength;
};


#endif // ERPC_TYPE_DEFINITIONS_TPAPPMANAGER


#endif // _TpAppManager_common_hpp_
