/* 项目名称,也是所有生成的源码文件名前缀 */

/*
 * Generated by erpcgen 1.14.0 on Fri Dec 12 15:17:41 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_TpAppManager_client_hpp_)
#define _TpAppManager_client_hpp_

#include "TpAppManager_interface.hpp"

#include "erpc_client_manager.h"

namespace erpcShim
{

class SystemApiService_client: public SystemApiService_interface
{
    public:
        SystemApiService_client(erpc::ClientManager *manager);

        virtual ~SystemApiService_client();

        /*! 当前运行应用进程信息 */
        virtual binary_t * TPR_RunAppProcessInfo(void);

        /*! 启动应用的UUID和进程pid */
        virtual bool TPR_StartApp(const binary_t * startParams);

        /*! 指定应用UUID终止进程 */
        virtual bool TPR_KillApp(const char * uuid);

        /*! 终止所有应用进程 */
        virtual bool TPR_KillAllApp(void);

    protected:
        erpc::ClientManager *m_clientManager;
};

} // erpcShim


#endif // _TpAppManager_client_hpp_
