/* 项目名称,也是所有生成的源码文件名前缀 */

/*
 * Generated by erpcgen 1.14.0 on Fri Dec 12 15:17:41 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_TpDesktopAPI_interface_hpp_)
#define _TpDesktopAPI_interface_hpp_

#include "TpDesktopAPI_common.hpp"

namespace erpcShim
{


// Abstract base class for SystemApiService
class SystemApiService_interface
{
    public:
        static const uint8_t m_serviceId = 1;
        static const uint8_t m_TPR_RunAppProcessInfoId = 1;
        static const uint8_t m_TPR_StartAppId = 2;
        static const uint8_t m_TPR_KillAppId = 3;
        static const uint8_t m_TPR_KillAllAppId = 4;

        virtual ~SystemApiService_interface(void);

        /*! 当前运行应用进程信息 */
        virtual binary_t * TPR_RunAppProcessInfo(void) = 0;

        /*! 启动应用的UUID和进程pid */
        virtual bool TPR_StartApp(const binary_t * startParams) = 0;

        /*! 指定应用UUID终止进程 */
        virtual bool TPR_KillApp(const char * uuid) = 0;

        /*! 终止所有应用进程 */
        virtual bool TPR_KillAllApp(void) = 0;
private:
};
} // erpcShim


#endif // _TpDesktopAPI_interface_hpp_
