/* 项目名称,也是所有生成的源码文件名前缀 */

/*
 * Generated by erpcgen 1.14.0 on Fri Dec 12 15:17:41 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_TpDesktopAPI_server_hpp_)
#define _TpDesktopAPI_server_hpp_

#include "TpDesktopAPI_interface.hpp"

#include "erpc_server.hpp"
#include "erpc_codec.hpp"

#if 11400 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif


namespace erpcShim
{

/*!
 * @brief Service subclass for SystemApiService.
 */
class SystemApiService_service : public erpc::Service
{
public:
    SystemApiService_service(SystemApiService_interface *_SystemApiService_interface);

    virtual ~SystemApiService_service();

    /*! @brief return service interface handler. */
    SystemApiService_interface* getHandler(void);

    /*! @brief Call the correct server shim based on method unique ID. */
    virtual erpc_status_t handleInvocation(uint32_t methodId, uint32_t sequence, erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, erpc::Transport * transport);

private:
    SystemApiService_interface *m_handler;
    /*! @brief Server shim for TPR_RunAppProcessInfo of SystemApiService interface. */
    erpc_status_t TPR_RunAppProcessInfo_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, erpc::Transport * transport, uint32_t sequence);

    /*! @brief Server shim for TPR_StartApp of SystemApiService interface. */
    erpc_status_t TPR_StartApp_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, erpc::Transport * transport, uint32_t sequence);

    /*! @brief Server shim for TPR_KillApp of SystemApiService interface. */
    erpc_status_t TPR_KillApp_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, erpc::Transport * transport, uint32_t sequence);

    /*! @brief Server shim for TPR_KillAllApp of SystemApiService interface. */
    erpc_status_t TPR_KillAllApp_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, erpc::Transport * transport, uint32_t sequence);
};

} // erpcShim


#endif // _TpDesktopAPI_server_hpp_
