/* 项目名称,也是所有生成的源码文件名前缀 */

/*
 * Generated by erpcgen 1.14.0 on Tue Dec 16 10:23:43 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_c_DeskService_client_h_)
#define _c_DeskService_client_h_

#include "DeskService_common.h"
#include "erpc_client_manager.h"

#if defined(__cplusplus)
extern "C"
{
#endif

#if !defined(ERPC_FUNCTIONS_DEFINITIONS)
#define ERPC_FUNCTIONS_DEFINITIONS


/*! @brief DeskServiceApi identifiers */
enum _DeskServiceApi_ids
{
    kDeskServiceApi_service_id = 1,
    kDeskServiceApi_DR_DesktSetService_id = 1,
    kDeskServiceApi_DR_DesktGetService_id = 2,
};

/*! 定义服务接口函数 */
//! @name DeskServiceApi
//@{
/*! 桌面服务输入RPC函数 */
bool DR_DesktSetService(const binary_t * params);

/*! 桌面服务输出RPC函数 */
binary_t * DR_DesktGetService(const binary_t * params);
//@}

#endif // ERPC_FUNCTIONS_DEFINITIONS

void initDeskServiceApi_client(erpc_client_t client);

void deinitDeskServiceApi_client(void);

#if defined(__cplusplus)
}
#endif

#endif // _c_DeskService_client_h_
