/* 项目名称,也是所有生成的源码文件名前缀 */

/*
 * Generated by erpcgen 1.14.0 on Tue Dec 16 10:23:43 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#include "c_DeskService_client.h"
#include "DeskService_client.hpp"
#include "erpc_manually_constructed.hpp"

using namespace erpc;
using namespace std;
using namespace erpcShim;


#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
DeskServiceApi_client *s_DeskServiceApi_client = nullptr;
#else
ERPC_MANUALLY_CONSTRUCTED_STATIC(DeskServiceApi_client, s_DeskServiceApi_client);
#endif

bool DR_DesktSetService(const binary_t * params)
{
    bool result;
    result = s_DeskServiceApi_client->DR_DesktSetService(params);

    return result;
}

binary_t * DR_DesktGetService(const binary_t * params)
{
    binary_t * result = NULL;
    result = s_DeskServiceApi_client->DR_DesktGetService(params);

    return result;
}

void initDeskServiceApi_client(erpc_client_t client)
{
#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
    erpc_assert(s_DeskServiceApi_client == nullptr);
    s_DeskServiceApi_client = new DeskServiceApi_client(reinterpret_cast<ClientManager *>(client));
#else
    erpc_assert(!s_DeskServiceApi_client.isUsed());
    s_DeskServiceApi_client.construct(reinterpret_cast<ClientManager *>(client));
#endif
}

void deinitDeskServiceApi_client(void)
{
#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
    if (s_DeskServiceApi_client != nullptr)
    {
        delete s_DeskServiceApi_client;
        s_DeskServiceApi_client = nullptr;
    }
#else
    s_DeskServiceApi_client.destroy();
#endif
}
