/* 项目名称,也是所有生成的源码文件名前缀 */

/*
 * Generated by erpcgen 1.14.0 on Tue Dec 16 10:23:43 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#include <new>
#include "c_DeskService_server.h"
#include "DeskService_server.hpp"
#include "erpc_manually_constructed.hpp"

using namespace erpc;
using namespace std;
using namespace erpcShim;


class DeskServiceApi_server: public DeskServiceApi_interface
{
    public:
        virtual ~DeskServiceApi_server() {};


        bool DR_DesktSetService(const binary_t * params)
        {
            bool result;
            result = ::DR_DesktSetService(params);

            return result;
        }

        binary_t * DR_DesktGetService(const binary_t * params)
        {
            binary_t * result = NULL;
            result = ::DR_DesktGetService(params);

            return result;
        }
};

ERPC_MANUALLY_CONSTRUCTED_STATIC(DeskServiceApi_service, s_DeskServiceApi_service);
ERPC_MANUALLY_CONSTRUCTED_STATIC(DeskServiceApi_server, s_DeskServiceApi_server);

erpc_service_t create_DeskServiceApi_service(void)
{
    erpc_service_t service;

#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
    service = new (nothrow) DeskServiceApi_service(new (nothrow)DeskServiceApi_server());
#else
    if (s_DeskServiceApi_service.isUsed())
    {
        service = NULL;
    }
    else
    {
        s_DeskServiceApi_server.construct();
        s_DeskServiceApi_service.construct(s_DeskServiceApi_server.get());
        service = s_DeskServiceApi_service.get();
    }
#endif

    return service;
}

void destroy_DeskServiceApi_service(erpc_service_t service)
{
#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
    if (service)
    {
        delete (DeskServiceApi_server *)(((DeskServiceApi_service *)service)->getHandler());
        delete (DeskServiceApi_service *)service;
    }
#else
    (void)service;
    erpc_assert(service == s_DeskServiceApi_service.get());
    s_DeskServiceApi_service.destroy();
    s_DeskServiceApi_server.destroy();
#endif
}

