/* 项目名称,也是所有生成的源码文件名前缀 */

/*
 * Generated by erpcgen 1.14.0 on Tue Dec 16 10:23:43 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_DeskService_server_hpp_)
#define _DeskService_server_hpp_

#include "DeskService_interface.hpp"

#include "erpc_server.hpp"
#include "erpc_codec.hpp"

#if 11400 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif


namespace erpcShim
{

/*!
 * @brief Service subclass for DeskServiceApi.
 */
class DeskServiceApi_service : public erpc::Service
{
public:
    DeskServiceApi_service(DeskServiceApi_interface *_DeskServiceApi_interface);

    virtual ~DeskServiceApi_service();

    /*! @brief return service interface handler. */
    DeskServiceApi_interface* getHandler(void);

    /*! @brief Call the correct server shim based on method unique ID. */
    virtual erpc_status_t handleInvocation(uint32_t methodId, uint32_t sequence, erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, erpc::Transport * transport);

private:
    DeskServiceApi_interface *m_handler;
    /*! @brief Server shim for DR_DesktSetService of DeskServiceApi interface. */
    erpc_status_t DR_DesktSetService_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, erpc::Transport * transport, uint32_t sequence);

    /*! @brief Server shim for DR_DesktGetService of DeskServiceApi interface. */
    erpc_status_t DR_DesktGetService_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, erpc::Transport * transport, uint32_t sequence);
};

} // erpcShim


#endif // _DeskService_server_hpp_
