/* 项目名称,也是所有生成的源码文件名前缀 */

/*
 * Generated by erpcgen 1.14.0 on Tue Dec 16 10:23:43 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_DeskService_client_hpp_)
#define _DeskService_client_hpp_

#include "DeskService_interface.hpp"

#include "erpc_client_manager.h"

namespace erpcShim
{

class DeskServiceApi_client: public DeskServiceApi_interface
{
    public:
        DeskServiceApi_client(erpc::ClientManager *manager);

        virtual ~DeskServiceApi_client();

        /*! 桌面服务输入RPC函数 */
        virtual bool DR_DesktSetService(const binary_t * params);

        /*! 桌面服务输出RPC函数 */
        virtual binary_t * DR_DesktGetService(const binary_t * params);

    protected:
        erpc::ClientManager *m_clientManager;
};

} // erpcShim


#endif // _DeskService_client_hpp_
