/* 项目名称,也是所有生成的源码文件名前缀 */

/*
 * Generated by erpcgen 1.14.0 on Tue Dec 16 10:23:43 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_DeskService_interface_hpp_)
#define _DeskService_interface_hpp_

#include "DeskService_common.hpp"

namespace erpcShim
{


// Abstract base class for DeskServiceApi
class DeskServiceApi_interface
{
    public:
        static const uint8_t m_serviceId = 1;
        static const uint8_t m_DR_DesktSetServiceId = 1;
        static const uint8_t m_DR_DesktGetServiceId = 2;

        virtual ~DeskServiceApi_interface(void);

        /*! 桌面服务输入RPC函数 */
        virtual bool DR_DesktSetService(const binary_t * params) = 0;

        /*! 桌面服务输出RPC函数 */
        virtual binary_t * DR_DesktGetService(const binary_t * params) = 0;
private:
};
} // erpcShim


#endif // _DeskService_interface_hpp_
