/* 项目名称,也是所有生成的源码文件名前缀 */

/*
 * Generated by erpcgen 1.14.0 on Tue Dec 16 10:23:43 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#include "DeskService_server.hpp"
#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
#include <new>
#include "erpc_port.h"
#endif
#include "erpc_manually_constructed.hpp"

#if 11400 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif

using namespace erpc;
using namespace std;
using namespace erpcShim;

#if ERPC_NESTED_CALLS_DETECTION
static bool nestingDetection;
#endif


//! @brief Function to read struct binary_t
static void read_binary_t_struct(erpc::Codec * codec, binary_t * data);


// Read struct binary_t function implementation
static void read_binary_t_struct(erpc::Codec * codec, binary_t * data)
{
    if(NULL == data)
    {
        return;
    }

    uint8_t * data_local;
    codec->readBinary(data->dataLength, &data_local);
    if (data->dataLength > 0)
    {
    data->data = (uint8_t *) erpc_malloc(data->dataLength * sizeof(uint8_t));
        if (data->data == NULL)
        {
            codec->updateStatus(kErpcStatus_MemoryError);
        }
        else
        {
            memcpy(data->data, data_local, data->dataLength);
        }
    }
    else
    {
        data->data = NULL;
    }
}


//! @brief Function to write struct binary_t
static void write_binary_t_struct(erpc::Codec * codec, const binary_t * data);


// Write struct binary_t function implementation
static void write_binary_t_struct(erpc::Codec * codec, const binary_t * data)
{
    if(NULL == data)
    {
        return;
    }

    codec->writeBinary(data->dataLength, data->data);
}


//! @brief Function to free space allocated inside struct binary_t
static void free_binary_t_struct(binary_t * data);


// Free space allocated inside struct binary_t function implementation
static void free_binary_t_struct(binary_t * data)
{
    erpc_free(data->data);
}



DeskServiceApi_service::DeskServiceApi_service(DeskServiceApi_interface *_DeskServiceApi_interface)
    : erpc::Service(DeskServiceApi_interface::m_serviceId)
    , m_handler(_DeskServiceApi_interface)
{
}

DeskServiceApi_service::~DeskServiceApi_service()
{
}

// return service interface handler.
DeskServiceApi_interface* DeskServiceApi_service::getHandler(void)
{
    return m_handler;
}

// Call the correct server shim based on method unique ID.
erpc_status_t DeskServiceApi_service::handleInvocation(uint32_t methodId, uint32_t sequence, Codec * codec, MessageBufferFactory *messageFactory, Transport * transport)
{
    erpc_status_t erpcStatus;
    switch (methodId)
    {
        case DeskServiceApi_interface::m_DR_DesktSetServiceId:
        {
            erpcStatus = DR_DesktSetService_shim(codec, messageFactory, transport, sequence);
            break;
        }

        case DeskServiceApi_interface::m_DR_DesktGetServiceId:
        {
            erpcStatus = DR_DesktGetService_shim(codec, messageFactory, transport, sequence);
            break;
        }

        default:
        {
            erpcStatus = kErpcStatus_InvalidArgument;
            break;
        }
    }

    return erpcStatus;
}

// Server shim for DR_DesktSetService of DeskServiceApi interface.
erpc_status_t DeskServiceApi_service::DR_DesktSetService_shim(Codec * codec, MessageBufferFactory *messageFactory, Transport * transport, uint32_t sequence)
{
    erpc_status_t err = kErpcStatus_Success;

    binary_t *params = NULL;
    params = (binary_t *) erpc_malloc(sizeof(binary_t));
    if (params == NULL)
    {
        codec->updateStatus(kErpcStatus_MemoryError);
    }
    bool result;

    // startReadMessage() was already called before this shim was invoked.

    read_binary_t_struct(codec, params);

    err = codec->getStatus();
    if (err == kErpcStatus_Success)
    {
        // Invoke the actual served function.
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = true;
#endif
        result = m_handler->DR_DesktSetService(params);
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = false;
#endif

        // preparing MessageBuffer for serializing data
        err = messageFactory->prepareServerBufferForSend(codec->getBufferRef(), transport->reserveHeaderSize());
    }

    if (err == kErpcStatus_Success)
    {
        // preparing codec for serializing data
        codec->reset(transport->reserveHeaderSize());

        // Build response message.
        codec->startWriteMessage(message_type_t::kReplyMessage, DeskServiceApi_interface::m_serviceId, DeskServiceApi_interface::m_DR_DesktSetServiceId, sequence);

        codec->write(result);

        err = codec->getStatus();
    }

    if (params)
    {
        free_binary_t_struct(params);
    }
    erpc_free(params);

    return err;
}

// Server shim for DR_DesktGetService of DeskServiceApi interface.
erpc_status_t DeskServiceApi_service::DR_DesktGetService_shim(Codec * codec, MessageBufferFactory *messageFactory, Transport * transport, uint32_t sequence)
{
    erpc_status_t err = kErpcStatus_Success;

    binary_t *params = NULL;
    params = (binary_t *) erpc_malloc(sizeof(binary_t));
    if (params == NULL)
    {
        codec->updateStatus(kErpcStatus_MemoryError);
    }
    binary_t * result = NULL;

    // startReadMessage() was already called before this shim was invoked.

    read_binary_t_struct(codec, params);

    err = codec->getStatus();
    if (err == kErpcStatus_Success)
    {
        // Invoke the actual served function.
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = true;
#endif
        result = m_handler->DR_DesktGetService(params);
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = false;
#endif

        // preparing MessageBuffer for serializing data
        err = messageFactory->prepareServerBufferForSend(codec->getBufferRef(), transport->reserveHeaderSize());
    }

    if (err == kErpcStatus_Success)
    {
        // preparing codec for serializing data
        codec->reset(transport->reserveHeaderSize());

        // Build response message.
        codec->startWriteMessage(message_type_t::kReplyMessage, DeskServiceApi_interface::m_serviceId, DeskServiceApi_interface::m_DR_DesktGetServiceId, sequence);

        write_binary_t_struct(codec, result);

        err = codec->getStatus();
    }

    if (params)
    {
        free_binary_t_struct(params);
    }
    erpc_free(params);

    if (result)
    {
        free_binary_t_struct(result);
    }
    erpc_free(result);

    return err;
}
