#!/bin/bash
# TpChart 示例程序交叉编译脚本
# 用法：./cross [CROSS_COMPILE_PREFIX]
# 示例：./cross aarch64-linux-gnu-

CROSS=${1:-aarch64-linux-gnu-}

${CROSS}g++ main.cpp MainWindowService.cpp -o TpChart \
    -I. \
    -I/usr/include \
    -I/usr/include/glib-2.0 \
    -I/usr/lib/x86_64-linux-gnu/glib-2.0/include \
    -I/usr/include/TinyPiX \
    -I/usr/include/TinyPiX/TpCore \
    -I/usr/include/TinyPiX/TpUtils \
    -I/usr/include/TinyPiX/TpGUI \
    -I/usr/include/TinyPiX/TpGUI/GUI \
    -I/usr/include/TinyPiX/TpGUI/Core \
    -I/usr/include/TinyPiX/TpGUI/Screen \
    -I/usr/include/TinyPiX/TpGUI/Widgets \
    -I/usr/include/TinyPiX/TpWM \
    -L/usr/lib \
    -L/usr/lib/TinyPiX \
    -lTpUtils -lTpGUI -lTpCore -lpthread -ldl
