/* 项目名称,也是所有生成的源码文件名前缀 */

/*
 * Generated by erpcgen 1.14.0 on Fri Nov 28 14:50:29 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_c_TpSystemApi_server_h_)
#define _c_TpSystemApi_server_h_

#include "TpSystemApi_common.h"

#if defined(__cplusplus)
extern "C"
{
#endif

typedef void * erpc_service_t;

#if !defined(ERPC_FUNCTIONS_DEFINITIONS)
#define ERPC_FUNCTIONS_DEFINITIONS


/*! @brief SystemApiService identifiers */
enum _SystemApiService_ids
{
    kSystemApiService_service_id = 1,
    kSystemApiService_TPR_RunAppProcessInfo_id = 1,
    kSystemApiService_TPR_StartApp_id = 2,
    kSystemApiService_TPR_KillApp_id = 3,
    kSystemApiService_TPR_KillAllApp_id = 4,
};

/*! 定义服务接口函数 */
//! @name SystemApiService
//@{
/*! 当前运行应用进程信息 */
binary_t * TPR_RunAppProcessInfo(void);

/*! 启动应用的UUID和进程pid */
bool TPR_StartApp(const char * uuid, int32_t pid);

/*! 指定应用UUID终止进程 */
bool TPR_KillApp(const char * uuid);

/*! 终止所有应用进程 */
bool TPR_KillAllApp(void);
//@}


#endif // ERPC_FUNCTIONS_DEFINITIONS

/*! @brief Return SystemApiService_service service object. */
erpc_service_t create_SystemApiService_service(void);

/*! @brief Destroy SystemApiService_service service object. */
void destroy_SystemApiService_service(erpc_service_t service);


#if defined(__cplusplus)
}
#endif

#endif // _c_TpSystemApi_server_h_
