/* 项目名称,也是所有生成的源码文件名前缀 */

/*
 * Generated by erpcgen 1.14.0 on Fri Nov 28 14:50:29 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#include "c_TpSystemApi_client.h"
#include "TpSystemApi_client.hpp"
#include "erpc_manually_constructed.hpp"

using namespace erpc;
using namespace std;
using namespace erpcShim;


#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
SystemApiService_client *s_SystemApiService_client = nullptr;
#else
ERPC_MANUALLY_CONSTRUCTED_STATIC(SystemApiService_client, s_SystemApiService_client);
#endif

binary_t * TPR_RunAppProcessInfo(void)
{
    binary_t * result = NULL;
    result = s_SystemApiService_client->TPR_RunAppProcessInfo();

    return result;
}

bool TPR_StartApp(const char * uuid, int32_t pid)
{
    bool result;
    result = s_SystemApiService_client->TPR_StartApp(uuid, pid);

    return result;
}

bool TPR_KillApp(const char * uuid)
{
    bool result;
    result = s_SystemApiService_client->TPR_KillApp(uuid);

    return result;
}

bool TPR_KillAllApp(void)
{
    bool result;
    result = s_SystemApiService_client->TPR_KillAllApp();

    return result;
}

void initSystemApiService_client(erpc_client_t client)
{
#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
    erpc_assert(s_SystemApiService_client == nullptr);
    s_SystemApiService_client = new SystemApiService_client(reinterpret_cast<ClientManager *>(client));
#else
    erpc_assert(!s_SystemApiService_client.isUsed());
    s_SystemApiService_client.construct(reinterpret_cast<ClientManager *>(client));
#endif
}

void deinitSystemApiService_client(void)
{
#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
    if (s_SystemApiService_client != nullptr)
    {
        delete s_SystemApiService_client;
        s_SystemApiService_client = nullptr;
    }
#else
    s_SystemApiService_client.destroy();
#endif
}
