/* 项目名称,也是所有生成的源码文件名前缀 */

/*
 * Generated by erpcgen 1.14.0 on Fri Nov 28 14:50:29 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#include <new>
#include "c_TpSystemApi_server.h"
#include "TpSystemApi_server.hpp"
#include "erpc_manually_constructed.hpp"

using namespace erpc;
using namespace std;
using namespace erpcShim;


class SystemApiService_server: public SystemApiService_interface
{
    public:
        virtual ~SystemApiService_server() {};


        binary_t * TPR_RunAppProcessInfo(void)
        {
            binary_t * result = NULL;
            result = ::TPR_RunAppProcessInfo();

            return result;
        }

        bool TPR_StartApp(const char * uuid, int32_t pid)
        {
            bool result;
            result = ::TPR_StartApp(uuid, pid);

            return result;
        }

        bool TPR_KillApp(const char * uuid)
        {
            bool result;
            result = ::TPR_KillApp(uuid);

            return result;
        }

        bool TPR_KillAllApp(void)
        {
            bool result;
            result = ::TPR_KillAllApp();

            return result;
        }
};

ERPC_MANUALLY_CONSTRUCTED_STATIC(SystemApiService_service, s_SystemApiService_service);
ERPC_MANUALLY_CONSTRUCTED_STATIC(SystemApiService_server, s_SystemApiService_server);

erpc_service_t create_SystemApiService_service(void)
{
    erpc_service_t service;

#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
    service = new (nothrow) SystemApiService_service(new (nothrow)SystemApiService_server());
#else
    if (s_SystemApiService_service.isUsed())
    {
        service = NULL;
    }
    else
    {
        s_SystemApiService_server.construct();
        s_SystemApiService_service.construct(s_SystemApiService_server.get());
        service = s_SystemApiService_service.get();
    }
#endif

    return service;
}

void destroy_SystemApiService_service(erpc_service_t service)
{
#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
    if (service)
    {
        delete (SystemApiService_server *)(((SystemApiService_service *)service)->getHandler());
        delete (SystemApiService_service *)service;
    }
#else
    (void)service;
    erpc_assert(service == s_SystemApiService_service.get());
    s_SystemApiService_service.destroy();
    s_SystemApiService_server.destroy();
#endif
}

