/* 项目名称,也是所有生成的源码文件名前缀 */

/*
 * Generated by erpcgen 1.14.0 on Thu Dec 11 15:55:07 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#include "TpAppManager_server.hpp"
#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
#include <new>
#include "erpc_port.h"
#endif
#include "erpc_manually_constructed.hpp"

#if 11400 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif

using namespace erpc;
using namespace std;
using namespace erpcShim;

#if ERPC_NESTED_CALLS_DETECTION
extern bool nestingDetection;
#endif


//! @brief Function to write struct binary_t
static void write_binary_t_struct(erpc::Codec * codec, const binary_t * data);


// Write struct binary_t function implementation
static void write_binary_t_struct(erpc::Codec * codec, const binary_t * data)
{
    if(NULL == data)
    {
        return;
    }

    codec->writeBinary(data->dataLength, data->data);
}


//! @brief Function to free space allocated inside struct binary_t
static void free_binary_t_struct(binary_t * data);


// Free space allocated inside struct binary_t function implementation
static void free_binary_t_struct(binary_t * data)
{
    erpc_free(data->data);
}



SystemApiService_service::SystemApiService_service(SystemApiService_interface *_SystemApiService_interface)
    : erpc::Service(SystemApiService_interface::m_serviceId)
    , m_handler(_SystemApiService_interface)
{
}

SystemApiService_service::~SystemApiService_service()
{
}

// return service interface handler.
SystemApiService_interface* SystemApiService_service::getHandler(void)
{
    return m_handler;
}

// Call the correct server shim based on method unique ID.
erpc_status_t SystemApiService_service::handleInvocation(uint32_t methodId, uint32_t sequence, Codec * codec, MessageBufferFactory *messageFactory, Transport * transport)
{
    erpc_status_t erpcStatus;
    switch (methodId)
    {
        case SystemApiService_interface::m_TPR_RunAppProcessInfoId:
        {
            erpcStatus = TPR_RunAppProcessInfo_shim(codec, messageFactory, transport, sequence);
            break;
        }

        case SystemApiService_interface::m_TPR_StartAppId:
        {
            erpcStatus = TPR_StartApp_shim(codec, messageFactory, transport, sequence);
            break;
        }

        case SystemApiService_interface::m_TPR_KillAppId:
        {
            erpcStatus = TPR_KillApp_shim(codec, messageFactory, transport, sequence);
            break;
        }

        case SystemApiService_interface::m_TPR_KillAllAppId:
        {
            erpcStatus = TPR_KillAllApp_shim(codec, messageFactory, transport, sequence);
            break;
        }

        default:
        {
            erpcStatus = kErpcStatus_InvalidArgument;
            break;
        }
    }

    return erpcStatus;
}

// Server shim for TPR_RunAppProcessInfo of SystemApiService interface.
erpc_status_t SystemApiService_service::TPR_RunAppProcessInfo_shim(Codec * codec, MessageBufferFactory *messageFactory, Transport * transport, uint32_t sequence)
{
    erpc_status_t err = kErpcStatus_Success;

    binary_t * result = NULL;

    // startReadMessage() was already called before this shim was invoked.

    err = codec->getStatus();
    if (err == kErpcStatus_Success)
    {
        // Invoke the actual served function.
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = true;
#endif
        result = m_handler->TPR_RunAppProcessInfo();
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = false;
#endif

        // preparing MessageBuffer for serializing data
        err = messageFactory->prepareServerBufferForSend(codec->getBufferRef(), transport->reserveHeaderSize());
    }

    if (err == kErpcStatus_Success)
    {
        // preparing codec for serializing data
        codec->reset(transport->reserveHeaderSize());

        // Build response message.
        codec->startWriteMessage(message_type_t::kReplyMessage, SystemApiService_interface::m_serviceId, SystemApiService_interface::m_TPR_RunAppProcessInfoId, sequence);

        write_binary_t_struct(codec, result);

        err = codec->getStatus();
    }

    if (result)
    {
        free_binary_t_struct(result);
    }
    erpc_free(result);

    return err;
}

// Server shim for TPR_StartApp of SystemApiService interface.
erpc_status_t SystemApiService_service::TPR_StartApp_shim(Codec * codec, MessageBufferFactory *messageFactory, Transport * transport, uint32_t sequence)
{
    erpc_status_t err = kErpcStatus_Success;

    char * uuid = NULL;
    int32_t pid;
    bool result;

    // startReadMessage() was already called before this shim was invoked.

    {
        uint32_t uuid_len;
        char * uuid_local;
        codec->readString(uuid_len, &uuid_local);
        uuid = (char*) erpc_malloc((uuid_len + 1) * sizeof(char));
        if ((uuid == NULL) || (uuid_local == NULL))
        {
            codec->updateStatus(kErpcStatus_MemoryError);
        }
        else
        {
            memcpy(uuid, uuid_local, uuid_len);
            (uuid)[uuid_len] = 0;
        }
    }

    codec->read(pid);

    err = codec->getStatus();
    if (err == kErpcStatus_Success)
    {
        // Invoke the actual served function.
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = true;
#endif
        result = m_handler->TPR_StartApp(uuid, pid);
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = false;
#endif

        // preparing MessageBuffer for serializing data
        err = messageFactory->prepareServerBufferForSend(codec->getBufferRef(), transport->reserveHeaderSize());
    }

    if (err == kErpcStatus_Success)
    {
        // preparing codec for serializing data
        codec->reset(transport->reserveHeaderSize());

        // Build response message.
        codec->startWriteMessage(message_type_t::kReplyMessage, SystemApiService_interface::m_serviceId, SystemApiService_interface::m_TPR_StartAppId, sequence);

        codec->write(result);

        err = codec->getStatus();
    }

    erpc_free(uuid);

    return err;
}

// Server shim for TPR_KillApp of SystemApiService interface.
erpc_status_t SystemApiService_service::TPR_KillApp_shim(Codec * codec, MessageBufferFactory *messageFactory, Transport * transport, uint32_t sequence)
{
    erpc_status_t err = kErpcStatus_Success;

    char * uuid = NULL;
    bool result;

    // startReadMessage() was already called before this shim was invoked.

    {
        uint32_t uuid_len;
        char * uuid_local;
        codec->readString(uuid_len, &uuid_local);
        uuid = (char*) erpc_malloc((uuid_len + 1) * sizeof(char));
        if ((uuid == NULL) || (uuid_local == NULL))
        {
            codec->updateStatus(kErpcStatus_MemoryError);
        }
        else
        {
            memcpy(uuid, uuid_local, uuid_len);
            (uuid)[uuid_len] = 0;
        }
    }

    err = codec->getStatus();
    if (err == kErpcStatus_Success)
    {
        // Invoke the actual served function.
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = true;
#endif
        result = m_handler->TPR_KillApp(uuid);
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = false;
#endif

        // preparing MessageBuffer for serializing data
        err = messageFactory->prepareServerBufferForSend(codec->getBufferRef(), transport->reserveHeaderSize());
    }

    if (err == kErpcStatus_Success)
    {
        // preparing codec for serializing data
        codec->reset(transport->reserveHeaderSize());

        // Build response message.
        codec->startWriteMessage(message_type_t::kReplyMessage, SystemApiService_interface::m_serviceId, SystemApiService_interface::m_TPR_KillAppId, sequence);

        codec->write(result);

        err = codec->getStatus();
    }

    erpc_free(uuid);

    return err;
}

// Server shim for TPR_KillAllApp of SystemApiService interface.
erpc_status_t SystemApiService_service::TPR_KillAllApp_shim(Codec * codec, MessageBufferFactory *messageFactory, Transport * transport, uint32_t sequence)
{
    erpc_status_t err = kErpcStatus_Success;

    bool result;

    // startReadMessage() was already called before this shim was invoked.

    err = codec->getStatus();
    if (err == kErpcStatus_Success)
    {
        // Invoke the actual served function.
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = true;
#endif
        result = m_handler->TPR_KillAllApp();
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = false;
#endif

        // preparing MessageBuffer for serializing data
        err = messageFactory->prepareServerBufferForSend(codec->getBufferRef(), transport->reserveHeaderSize());
    }

    if (err == kErpcStatus_Success)
    {
        // preparing codec for serializing data
        codec->reset(transport->reserveHeaderSize());

        // Build response message.
        codec->startWriteMessage(message_type_t::kReplyMessage, SystemApiService_interface::m_serviceId, SystemApiService_interface::m_TPR_KillAllAppId, sequence);

        codec->write(result);

        err = codec->getStatus();
    }

    return err;
}
