/* 项目名称,也是所有生成的源码文件名前缀 */

/*
 * Generated by erpcgen 1.14.0 on Tue Nov 25 17:33:09 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_TpSystemApi_common_h_)
#define _TpSystemApi_common_h_


#if defined(__cplusplus)
extern "C"
{
#endif
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "erpc_version.h"

#if 11400 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif


#if !defined(ERPC_TYPE_DEFINITIONS_TPSYSTEMAPI)
#define ERPC_TYPE_DEFINITIONS_TPSYSTEMAPI

// Aliases data types declarations
typedef struct list_string_1_t list_string_1_t;
typedef struct binary_t binary_t;

// Structures/unions data types declarations
struct list_string_1_t
{
    char ** elements;
    uint32_t elementsCount;
};

struct binary_t
{
    uint8_t * data;
    uint32_t dataLength;
};


#endif // ERPC_TYPE_DEFINITIONS_TPSYSTEMAPI

#if defined(__cplusplus)
}
#endif

#endif // _TpSystemApi_common_h_
