/* 项目名称,也是所有生成的源码文件名前缀 */

/*
 * Generated by erpcgen 1.14.0 on Tue Nov 25 17:33:09 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_TpSystemApi_interface_hpp_)
#define _TpSystemApi_interface_hpp_

#include "TpSystemApi_common.hpp"

namespace erpcShim
{


// Abstract base class for SystemApiService
class SystemApiService_interface
{
    public:
        static const uint8_t m_serviceId = 1;
        static const uint8_t m_TPR_RunAppProcessInfoId = 1;
        static const uint8_t m_TPR_StartAppId = 2;
        static const uint8_t m_TPR_KillAppId = 3;
        static const uint8_t m_TPR_KillAllAppId = 4;

        virtual ~SystemApiService_interface(void);

        /*! 当前运行应用进程信息 */
        virtual binary_t * TPR_RunAppProcessInfo(void) = 0;

        /*! 指定UUID启动应用 */
        virtual bool TPR_StartApp(const char * uuid, const list_string_1_t * args) = 0;

        /*! 指定应用UUID终止进程 */
        virtual bool TPR_KillApp(const char * uuid) = 0;

        /*! 终止所有应用进程 */
        virtual bool TPR_KillAllApp(void) = 0;
private:
};
} // erpcShim


#endif // _TpSystemApi_interface_hpp_
