/* 项目名称,也是所有生成的源码文件名前缀 */

/*
 * Generated by erpcgen 1.14.0 on Fri Nov 28 14:50:29 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#include "TpSystemApi_interface.hpp"

#if 11400 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif


using namespace std;
using namespace erpcShim;

SystemApiService_interface::~SystemApiService_interface(void)
{
}
