/* 项目名称,也是所有生成的源码文件名前缀 */

/*
 * Generated by erpcgen 1.14.0 on Fri Nov 28 14:50:29 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_TpSystemApi_common_hpp_)
#define _TpSystemApi_common_hpp_


#include <cstddef>
#include <cstdint>

#include "erpc_version.h"

#if 11400 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif


#if !defined(ERPC_TYPE_DEFINITIONS_TPSYSTEMAPI)
#define ERPC_TYPE_DEFINITIONS_TPSYSTEMAPI

// Aliases data types declarations
typedef struct binary_t binary_t;

// Structures/unions data types declarations
struct binary_t
{
    uint8_t * data;
    uint32_t dataLength;
};


#endif // ERPC_TYPE_DEFINITIONS_TPSYSTEMAPI


#endif // _TpSystemApi_common_hpp_
