# 平台不同拷贝资源文件到不同安装目录；以及准备不同平台的安装依赖库
# 首选方案：使用 CMAKE_CROSSCOMPILING 和自定义变量
if(DEFINED TARGET_ARCH)
    # 显式指定目标架构优先
    if(TARGET_ARCH STREQUAL "x86_64")
        message(STATUS "============ 目标平台: X86_64 ============")
        set(INSTALL_PACKAGE_ROOT_PATH "${CMAKE_CURRENT_SOURCE_DIR}/install/x86_64")
        set(DEPEND_LIB_PATH "${CMAKE_CURRENT_SOURCE_DIR}/src/depend_lib/dynamic/x86_64")
    elseif(TARGET_ARCH STREQUAL "arm64" OR TARGET_ARCH STREQUAL "aarch64")
        message(STATUS "============ 目标平台: ARM64 ============")
        set(INSTALL_PACKAGE_ROOT_PATH "${CMAKE_CURRENT_SOURCE_DIR}/install/arm_64")
        set(DEPEND_LIB_PATH "${CMAKE_CURRENT_SOURCE_DIR}/src/depend_lib/dynamic/arm_64")
    endif()
elseif(CMAKE_CROSSCOMPILING)
    # 交叉编译时获取目标架构
    message(STATUS "============ 交叉编译目标平台: ${CMAKE_SYSTEM_NAME}-${CMAKE_SYSTEM_PROCESSOR} ============")
    
    if(CMAKE_SYSTEM_PROCESSOR MATCHES "arm|aarch64")
        set(INSTALL_PACKAGE_ROOT_PATH "${CMAKE_CURRENT_SOURCE_DIR}/install/arm_64")
        set(DEPEND_LIB_PATH "${CMAKE_CURRENT_SOURCE_DIR}/src/depend_lib/dynamic/arm_64")
    elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "x86|i686|i386|AMD64")
        set(INSTALL_PACKAGE_ROOT_PATH "${CMAKE_CURRENT_SOURCE_DIR}/install/x86_64")
        set(DEPEND_LIB_PATH "${CMAKE_CURRENT_SOURCE_DIR}/src/depend_lib/dynamic/x86_64")
    else()
        message(WARNING "未知的目标平台架构: ${CMAKE_SYSTEM_PROCESSOR}")
    endif()
else()
    # 本机编译
    if(CMAKE_SYSTEM_PROCESSOR MATCHES "x86|i686|i386|AMD64")
        message(STATUS "============ 本机平台: X86_64 ============")
        set(INSTALL_PACKAGE_ROOT_PATH "${CMAKE_CURRENT_SOURCE_DIR}/install/x86_64")
        set(DEPEND_LIB_PATH "${CMAKE_CURRENT_SOURCE_DIR}/src/depend_lib/dynamic/x86_64")
    elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "arm|aarch64")
        message(STATUS "============ 本机平台: ARM ============")
        set(INSTALL_PACKAGE_ROOT_PATH "${CMAKE_CURRENT_SOURCE_DIR}/install/arm_64")
        set(DEPEND_LIB_PATH "${CMAKE_CURRENT_SOURCE_DIR}/src/depend_lib/dynamic/arm_64")
    endif()
endif()