# 平台不同拷贝资源文件到不同安装目录；以及准备不同平台的安装依赖库
# 首选方案：使用 CMAKE_CROSSCOMPILING 和自定义变量

# 首先检测指针大小以确定32位/64位架构[1,8](@ref)
if(CMAKE_SIZEOF_VOID_P EQUAL 8)
    set(ARCH_BIT 64)
elseif(CMAKE_SIZEOF_VOID_P EQUAL 4)
    set(ARCH_BIT 32)
else()
    set(ARCH_BIT 64)
endif()

if(CMAKE_CROSSCOMPILING)
    # 交叉编译时获取目标架构
    if(CMAKE_SYSTEM_PROCESSOR MATCHES "^(aarch64|arm64)$")
        message(STATUS "============ 交叉编译;目标平台：arm64 ============")
        set(PLATFORM_NAME "arm_64")
    elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "^(arm|arm32|armv[0-9]+|aarch32)$")
        message(STATUS "============ 交叉编译;目标平台：arm32 ============")
        set(PLATFORM_NAME "arm_32")
    elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "^(x86_64|amd64|AMD64)$")
        message(STATUS "============ 交叉编译;目标平台：x86_64 ============")
        set(PLATFORM_NAME "x86_64")
    elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "^(i[3-6]86|i386|x86)$")
        message(STATUS "============ 交叉编译;目标平台：x86_32 ============")
        set(PLATFORM_NAME "x86_32")
    else()
        message(WARNING "未知的目标平台架构: ${CMAKE_SYSTEM_PROCESSOR}")
        if(ARCH_BIT EQUAL 64)
            set(PLATFORM_NAME "x86_64")
        else()
            set(PLATFORM_NAME "x86_32")
        endif()
    endif()
else()
        # 本机构建
    if(CMAKE_SYSTEM_PROCESSOR MATCHES "^(x86_64|amd64|AMD64)$")
        message(STATUS "============ 本机编译;目标平台：x86_64 ============")
        set(PLATFORM_NAME "x86_64")
    elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "^(i[3-6]86|i386|x86)$")
        message(STATUS "============ 本机编译;目标平台：x86_32 ============")
        set(PLATFORM_NAME "x86_32")
    elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "^(aarch64|arm64)$")
        message(STATUS "============ 本机编译;目标平台：arm64 ============")
        set(PLATFORM_NAME "arm_64")
    elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "^(arm|arm32|armv[0-9]+|aarch32)$")
        message(STATUS "============ 本机编译;目标平台：arm32 ============")
        set(PLATFORM_NAME "arm_32")
    else()
        message(WARNING "未知的目标平台架构: ${CMAKE_SYSTEM_PROCESSOR}")
        set(PLATFORM_NAME "x86_64")
    endif()
endif()

set(INSTALL_PACKAGE_ROOT_PATH "${CMAKE_SOURCE_DIR}/install/${PLATFORM_NAME}")
set(DEPEND_DYNAMIC_LIB_PATH "${CMAKE_SOURCE_DIR}/src/depend_lib/dynamic/${PLATFORM_NAME}")
set(DEPEND_STATIC_LIB_PATH "${CMAKE_SOURCE_DIR}/src/depend_lib/static/${PLATFORM_NAME}")

# 设置输出目录（根据架构和构建类型）
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${INSTALL_PACKAGE_ROOT_PATH}/bin)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${INSTALL_PACKAGE_ROOT_PATH}/lib)
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${INSTALL_PACKAGE_ROOT_PATH}/lib)
